### ISSUE TITLE
Can't create project.

### ISSUE THREAD

**Issue by BonarBeavis** [Scifabric/pbs#48]
`$ pbs` throws following error:
```bash
Traceback (most recent call last):
  File "/home/beavis/.local/bin/pbs", line 7, in <module>
    from pbs import cli
  File "/home/beavis/.local/lib/python3.5/site-packages/pbs.py", line 30, in <module>
    import pbclient
  File "/usr/local/lib/python3.5/dist-packages/pbclient/__init__.py", line 182
    print OFFSET_WARNING
                       ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by teleyinex** [comment]
Are you running Python v3? Then, yes, it fails. We only support for the moment python 2.7. We're testing the migration to python >= 3.5

**Comment by BonarBeavis** [comment]
Thanks, I am running py3...
